### ISSUE TITLE
QTWeb 3.8.5 Javascript Error

### ISSUE THREAD

**Issue by hirasso** [metafizzy/fizzy-ui-utils#11]
Hi @desandro ,

I can totally imagine you have better things to do, but still thought I'll let you know this one: 

I've taken on the task of creating PDFs from a website I built, that makes heavy usage of Flickity and Isotope. The library of choice for the PDF creation is [wkhtmltopdf](https://wkhtmltopdf.org/). They are using the browser [QTWeb](http://www.qtweb.net/download.html) to render the page and convert it to a PDF. Here is a minimal example of the terminal command with javascript debugging enabled:

```shell
$ wkhtmltopdf --debug-javascript http://my-site.com/my-page/ test.pdf
```
It's working fine, except of this Javascript error:
```
Warning: undefined:0 TypeError: 'undefined' is not a function
```
...not very verbose, I know it's a pain ;) 

To investigate where this error is coming from, I debugged the site [as described here](https://stackoverflow.com/a/33140006/586823) (the MAC version seems to be broken in Mojave, I'm using the windows version with Virtual Box).

It's actually coming from a function inside of `fizzy-ui-utils/utils.js`:

![Screen Shot 2019-04-15 at 16 18 12](https://user-images.githubusercontent.com/869813/56140555-688ab080-5f9b-11e9-8f21-d9dd5828904b.jpg)

So the actual error is this:
```
TypeError: 'undefined' is not a function (evaluating 'elem.getAttribute( dataAttr )')
```
I would be very happy if you could take a look at this. It might be an easy fix, who knows...

**Comment by desandro** [comment]
Thanks for reporting this issue.

As I read this issue, it seems the problem is that HTML initialization is being used on items that are not Elements.

Another issue is that I'm not sure if Metafizzy JS supports QTWeb. THe current versions are designed to work in IE11, Safari 9, Chrome 33, etc. QTWeb hasn't been updated since 2013. It may work with older versions like Flickity v1 and Isotope v2.

**Comment by hirasso** [comment]
Hi @desandro , thanks for your answer.

...I ended up completely disabling Flickity and Isotope for PDF requests and rendering a simplified layout of the images.
