### ISSUE TITLE
modulo

### ISSUE THREAD

**Issue by yaroslavert** [metafizzy/fizzy-ui-utils#7]
I do not know English well

question
   what work function(meton|property) modulo

**Comment by desandro** [comment]
``` js
utils.modulo( 3, 3 ) // => 0
utils.modulo( 4, 3 ) // => 1
utils.modulo( 5, 3 ) // => 2
utils.modulo( 6, 3 ) // => 0
```

**Comment by yaroslavert** [comment]
when it should be used

**Comment by yaroslavert** [comment]
this function(3,3) === 3 % 3

**Comment by desandro** [comment]
ah, yes! But the trouble with `%` in JS is that it works it's a remainder operator, not a modulo operator.

``` js
-4 % 3 // => -1
utils.modulo( -4, 3 ) // => 2
```

**Comment by yaroslavert** [comment]
the operator is not working properly

**Comment by yaroslavert** [comment]
the operator % is not work wrong
